---
kind: pipeline
name: AArch64 CI
platform:
  arch: arm64
trigger:
  event:
    - custom
steps:
  - name: prepare
    image: alpine:3.12
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - /bin/ash bin/ci-aarch64-alpine-build.sh prepare
  - name: stdlib_spec
    image: alpine:3.12
    depends_on:
      - prepare
    commands:
      - /bin/ash bin/ci-aarch64-alpine-build.sh std_spec
  - name: compiler_spec
    image: alpine:3.12
    depends_on:
      - prepare
    commands:
      - /bin/ash bin/ci-aarch64-alpine-build.sh compiler_spec
