arch: arm64
os: linux
language: c
services:
  - docker
script: docker run -e GITHUB_TOKEN -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -v "$(pwd)":/crystal alpine:3.12 /bin/ash /crystal/bin/ci-aarch64-alpine-build.sh
